### ISSUE TITLE
Node Manager fails to communicate properly on TCP

### ISSUE THREAD

**Issue by ldbalk** [dvmartin999/jaustoolset#4]
What steps will reproduce the problem?
When the Node Manager configuration file specifies only TCP, the first message will be received by the destination node but no messages after that.  Restarting the Node Manager repeats the same problem.  UDP communications must be disabled in the Node Manager for this to be observed.

What is the expected output? 
The destination node should see receive the messages being sent.  The Node Manager log (with logging set to Level 5) should show valid TCP messages being both sent and received.

What do you see instead?
TCP messages after the first one are not delivered.  The log messages show that TCP messages are being sent, but most of them are not being interpreted as valid TCP messages.  Those that are listed as valid show an incorrect size for the message.

What version of the product are you using? 
v2.2.1

On what operating system?
Ubuntu 14.04 LTS

Please provide any additional information below.
None.

**Comment by dvmartin999** [comment]
Fixed an issue regarding copy in place in Archive::removeAt, primarily impacting TCP/IP. Problem manifested under 14.04, but is likely compiler dependent.
